name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    env:
      my_secret: ${{secrets.commit_secret}}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@main

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Get yarn cache directory path 🛠
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules 📦
        uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies 👨🏻‍💻
        run: yarn

      - name: Run linter 👀
        run: yarn lint

      - name: Deploy gh-pages 📡
        run:
          cd dist
          git init
          git config --global user.email git@jaimeblasco.com
          git config --global user.name jamesblasco
          git status
          git remote add origin "https://jamesblasco:${{secrets.commit_secret}}@github.com/Flutter-Madrid/flutter.madrid.git"
          git checkout -b gh-pages
          echo "flutter.madrid" > CNAME
          git add --all
          git commit -m ":rocket: Roll master - Deploy website"
          git push origin gh-pages -f
